services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: redhound
      POSTGRES_PASSWORD: redhound
      POSTGRES_DB: api_pwn_lab
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: redhound
      DATABASE_PASSWORD: redhound
      DATABASE_NAME: api_pwn_lab
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app          # Mount host folder into container for live reload
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start:dev"  # start in dev mode with hot reload

volumes:
  db-data: